LIST_DOCS = """"
THIS IS GOOD LIST EPHRAIM
"""
CREATE_DOCS = """"
THIS IS GOOD CREATE EPHRAIM
"""
RETRIEVE_DOCS = """"
THIS IS GOOD RETRIEVE EPHRAIM
"""
UPDATE_DOCS = """"
THIS IS GOOD UPDATE EPHRAIM
"""
PARTIAL_UPDATE_DOCS = """"
THIS IS GOOD PARTIAL_UPDATE EPHRAIM
"""
DELETE_DOCS = """"
THIS IS GOOD DELETE EPHRAIM
"""
